---
- name: php repository gpg key (stretch only)
  become: yes
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    state: present
  when: raspbian_version.stdout == 'stretch'

- name: php repository (stretch only)
  become: yes
  apt_repository:
    repo: deb https://packages.sury.org/php/ stretch main
    filename: php7.list
    state: present
  when: raspbian_version.stdout == 'stretch'

- name: php repository gpg key (buster only)
  become: yes
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    state: present
  when: raspbian_version.stdout == 'buster'

- name: php repository (buster only)
  become: yes
  apt_repository:
    repo: deb https://packages.sury.org/php/ buster main
    filename: php7.list
    state: present
  when: raspbian_version.stdout == 'buster'

- name: install the package, force upgrade
  pip: 
    name: numpy
    extra_args: --upgrade

- name: install nginx
  become: yes
  apt:
    update_cache: no
    state: present
    name: nginx

- name: install php
  become: yes
  apt:
    update_cache: no
    state: present
    name:
      - php7.4-fpm
      - php7.4-mbstring
      - php7.4-sqlite3

- name: install composer
  become: yes
  apt:
    update_cache: no
    state: present
    name: composer

- name: add pi user to www-data group
  become: yes
  user:
    name: pi
    groups: www-data
    append: yes

- name: web directory
  become: yes
  file:
    path: "{{ web_home }}"
    state: directory
    owner: pi
    group: www-data
    mode: 0775

- name: config directory
  become: yes
  file:
    path: "{{ web_home }}/Config"
    state: directory
    owner: pi
    group: www-data
    mode: 0775

- name: php config file
  become: yes
  template:
    src: Config.php.j2
    dest: "{{ web_home }}/Config/Config.php"
    owner: pi
    group: www-data
    mode: 0644

- name: nginx config file
  become: yes
  template:
    src: nginx_default.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: nginx non-tls config symlink
  become: yes
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
    owner: root
    group: root
  when: enable_non_tls|bool
  notify: restart nginx

- name: remove non-tls site enable if disabled
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  when: not enable_non_tls|bool
  notify: restart nginx

- name: update images directory group
  become: yes
  file:
    path: "{{ images_output }}"
    state: directory
    group: www-data

- name: update thumbnails directory group
  become: yes
  file:
    path: "{{ images_output }}/thumb"
    state: directory
    group: www-data

- name: update videos directory group
  become: yes
  file:
    path: "{{ videos_output }}"
    state: directory
    group: www-data

- name: update database folder permissions
  become: yes
  file:
    path: "{{ noaa_home }}/db"
    group: www-data
    mode: 0770

- name: update database file permissions
  become: yes
  file:
    path: "{{ noaa_home }}/db/panel.db"
    group: www-data
    mode: 0770

#- name: check if self-signed certificate is expired
#  command: openssl x509 -checkend 86400 -noout -in /etc/ssl/certs/local_server.crt
#  register: cert_valid
#  failed_when: no
#  changed_when: no
#  when: enable_tls|bool

#- name: create self-signed certificate
#  become: yes
#  command: >
#    openssl req -x509 -nodes -subj '/CN={{ web_server_name }}' -days {{ cert_valid_days }}
#    -newkey rsa:4096 -sha256 -keyout {{ tls_cert_key }} -out {{ tls_cert }}
#  when: enable_tls|bool and cert_valid.rc != 0

- name: nginx tls config file
  become: yes
  template:
    src: nginx_tls_default.j2
    dest: /etc/nginx/sites-available/default-tls
    owner: root
    group: root
    mode: 0644
  when: enable_tls|bool
  notify: restart nginx

- name: nginx tls config symlink
  become: yes
  file:
    src: /etc/nginx/sites-available/default-tls
    dest: /etc/nginx/sites-enabled/default-tls
    state: link
    owner: root
    group: root
  when: enable_tls|bool
  notify: restart nginx

- name: remove tls site enable if disabled
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default-tls
    state: absent
  when: not enable_tls|bool
  notify: restart nginx

- name: ensure nginx is running
  become: yes
  service:
    name: nginx
    state: started

- name: www-data sudoers atrm as pi user
  become: yes
  copy:
    src: 020_www-data-atrm-nopasswd
    dest: /etc/sudoers.d/020_www-data-atrm-nopasswd
    owner: root
    group: root
    mode: 0440
...
