---
- name: noaa environment variables
  template:
    src: noaa-v2.conf.j2
    dest: ~pi/.noaa-v2.conf
    owner: pi
    group: pi
    mode: 0644

- name: predict directory
  file:
    path: ~pi/.predict
    state: directory
    owner: pi
    group: pi
    mode: 0755

- name: predict config file
  template:
    src: predict.qth.j2
    dest: ~pi/.predict/predict.qth
    owner: pi
    group: pi
    mode: 0644

- name: wxtoimg config file
  template:
    src: wxtoimgrc
    dest: ~pi/.wxtoimgrc
    owner: pi
    group: pi
    mode: 0644

- name: wxtoimg license terms acceptance file
  copy:
    src: wxtoimglic
    dest: ~pi/.wxtoimglic
    owner: pi
    group: pi
    mode: 0644

- name: log directory for raspberry-noaa-v2 logs
  become: yes
  file:
    path: /var/log/raspberry-noaa-v2
    state: directory
    owner: pi
    group: pi
    mode: 0755

- name: logrotate settings for raspberry-noaa-v2 logs
  become: yes
  copy:
    src: logrotate-settings
    dest: /etc/logrotate.d/raspberry-noaa-v2
    owner: root
    group: root
    mode: 0644

- name: gnuradio home directory
  file:
    path: ~pi/.gnuradio
    state: directory
    owner: pi
    group: pi
    mode: 0755

- name: gnuradio prefs directory
  file:
    path: ~pi/.gnuradio/prefs
    state: directory
    owner: pi
    group: pi
    mode: 0755

- name: gnuradio prefs file
  copy:
    src: vmcircbuf_default_factory
    dest: ~pi/.gnuradio/prefs/vmcircbuf_default_factory
    owner: pi
    group: pi
    mode: 0644
...
