---
# environment configuration files
- include: configs.yml

# dependent packages and libs to be installed
- include: dependencies.yml

# ntp configurations
- include: ntp.yml

# core software modules
- include: sdr.yml

# tools and utilities
- include: tools.yml

# ramfs setup
- include: ramfs.yml
...
