---
# available languages for webpanel (see "Lang" directory files)
available_langs: [ ar, bg, cn, de, en, es, fr, lt, nl, pt, sr ]

# root git clone directory (where functionality exists)
noaa_home: "/home/pi/raspberry-noaa-v2"

# database file
db_file: "{{ noaa_home }}/db/panel.db"

# website content directory
web_home: "/var/www/wx-new"

# output root directories for images, audio, and video
output_root: /srv
images_output: "{{ output_root }}/images"
audio_output: "{{ output_root }}/audio"
videos_output: "{{ output_root }}/videos"

# file used for NOAA animations
noaa_animation_output: "{{ videos_output }}/RollingAnimation.webm"

# ramfs location
ramfs_path: "/var/ramfs"

# log output file
log_file: "/var/log/raspberry-noaa-v2/output.log"

# TLS self-signed certs
tls_cert: /etc/letsencrypt/live/{{ web_server_name }}/fullchain.pem
tls_cert_key: /etc/letsencrypt/live/{{ web_server_name }}/privkey.pem
tls_trusted_certificate: /etc/letsencrypt/live/{{ web_server_name }}/chain.pem
...
